from MIDIFileGenerator import Scales

class sakura:

    def __init__(self):
        self.name = 'Sakura'
        self.sakura = Scales(200)

    def generator(self):
        #------- 1 -------#
        '''self.sakura.d6(0.7)
        self.sakura.d6s(0.7)
        #------- 2 -------#
        self.sakura.d5s(5.6)
        self.sakura.modify_time(-5.5)
        self.sakura.a5(5.5)
        self.sakura.modify_time(-5.4)
        self.sakura.c6(5.4)
        self.sakura.modify_time(-5.3)
        self.sakura.f6(5.3)
        #------- 3 -------#
        self.sakura.a5(1.4)
        self.sakura.d6(1.4)
        self.sakura.d6s(1.4)
        self.sakura.d6(1.4)
        #------- 4/5 -------#
        self.sakura.c6(1.4)
        self.sakura.d6(1.4)
        self.sakura.d6s(1.4)
        self.sakura.a5s(4.2)
        self.sakura.modify_time(-4.2)
        self.sakura.d6(4.2)
        self.sakura.a5(1.4)
        self.sakura.a5s(1.4)
        self.sakura.modify_time(-11.2)
        self.sakura.d4(1.4)
        self.sakura.modify_time(-1.4)
        self.sakura.f4(1.4)
        self.sakura.a4s(1.4)
        self.sakura.c5(1.4)
        self.sakura.f5(4.2)
        self.sakura.modify_time(2.8)
        #------- 6/7 -------#
        self.sakura.d5s(1.4)
        self.sakura.modify_time(-1.4)
        self.sakura.c6(1.4)
        self.sakura.d6(1.4)
        self.sakura.d6s(1.4)
        self.sakura.a5(2.8)
        self.sakura.modify_time(-2.8)
        self.sakura.f6(2.8)
        self.sakura.d6(1.4)
        self.sakura.a5(1.4)
        self.sakura.modify_time(-1.4)
        self.sakura.f6(1.4)
        self.sakura.a6(1.4)
        self.sakura.modify_time(-11.2)
        self.sakura.c4(1.4)
        self.sakura.a4s(1.4)
        self.sakura.d5s(1.4)
        self.sakura.c5(7)'''
        #------- 8/9 -------#
        self.sakura.c6(2.1)
        self.sakura.modify_time(-2.1)
        self.sakura.a6(2.1)
        self.sakura.a6s(2.1)
        self.sakura.a5(2.8)
        self.sakura.modify_time(-2.8)
        self.sakura.f6(2.8)
        self.sakura.d6s(1.4)
        self.sakura.a5s(1.4)
        self.sakura.modify_time(-1.4)
        self.sakura.d6(1.4)
        self.sakura.a5s(1.4)
        self.sakura.modify_time(-11.2)
        self.sakura.a3s(2.1)
        self.sakura.modify_time(-1.9)
        self.sakura.f4(1.9)
        self.sakura.modify_time(-1.7)
        self.sakura.c5(1.7)
        self.sakura.d5(2.1)
        self.sakura.a4s(7)
        #------- 10 -------#
        self.sakura.a5(5.6)
        self.sakura.modify_time(-5.6)
        self.sakura.f6(5.6)
        self.sakura.modify_time(-5.6)
        self.sakura.d4s(1.4)
        self.sakura.a4s(1.4)
        self.sakura.d5(2.8)
        self.sakura.modify_time(-2.8)
        self.sakura.g5(2.8)
        #------- 11 -------#
        self.sakura.a5(1.4)
        self.sakura.d6(1.4)
        self.sakura.a5(1.4)
        self.sakura.modify_time(-1.4)
        self.sakura.d6s(1.4)
        self.sakura.d6(1.4)
        self.sakura.modify_time(-5.6)
        self.sakura.d4s(1.4)
        self.sakura.c5(1.4)
        self.sakura.f5(2.8)
        #------- 12/13 -------#
        self.sakura.f5(1.4)
        self.sakura.modify_time(-1.4)
        self.sakura.c6(1.4)
        self.sakura.a5s(1.4)
        self.sakura.modify_time(-1.4)
        self.sakura.d6(1.4)
        self.sakura.c6(1.4)
        self.sakura.modify_time(-1.4)
        self.sakura.d6s(1.4)
        self.sakura.a5s(2.8)
        self.sakura.modify_time(-2.8)
        self.sakura.d6(2.8)
        self.sakura.d6(1.4)
        self.sakura.d6(1.4)
        self.sakura.modify_time(-1.4)
        self.sakura.f6(1.4)
        self.sakura.a6(1.4)
        self.sakura.modify_time(-11.2)
        self.sakura.c4(1.4)
        self.sakura.a4s(1.4)
        self.sakura.c5(1.4)
        self.sakura.f5(4.2)
        self.sakura.a4s(2.8)



        with open(self.name, "wb") as output_file:
            self.sakura.get_midi().writeFile(output_file)
        return self.name